block classes function
CodePilotSE/CoPiStarter pull request #15
Opened 2024-12-20 10:10 UTC by FilipKumlin

2025-02-21 10:19 UTC, simonwimell requested changes
Utöver min lilla kommentar, borde hela blocket döpas om till "DEMO block" eller liknande?

2025-02-21 10:19 UTC, simonwimell commented on blocks/social-links/block.json
> +	"parent": [],
skulle du verkligen ha en tom "parent" här?

2025-02-21 10:33 UTC, FilipKumlin commented on blocks/social-links/block.json
> +	"parent": [],
```suggestion
```

2025-03-07 10:24 UTC, simonwimell commented
Jag kommenterade ovan "borde hela blocket döpas om till "DEMO block" eller liknande?" @FilipKumlin

2025-03-24 10:29 UTC, simonwimell approved these changes

2025-03-24 10:30 UTC, merged